// <auto-generated />
namespace SEMYPROJECT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createdb6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdb6));
        
        string IMigrationMetadata.Id
        {
            get { return "202106090405286_createdb6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
